document.write("<footer class=\"footer-bg\">");
document.write("	<section class=\"footer-area ptb\">");
document.write("		<div class=\"container\">");
document.write("			<div class=\"row\">");
document.write("				<div class=\"col-lg-4 col-md-6 col-sm-6 md-mb-20\">");
document.write("					<div class=\"footer-about\">");
document.write("						<a href=\"index.html\">");
document.write("							<img class=\"img-fluid\"src=\".\/static\/image\/logo_white.png\" alt=\"logo\">");
document.write("						<\/a>");
document.write("						<p>");
document.write("							At guo-link Technology, we pursue innovation without and create the future with technology. With passion, wisdom, we blend dreams and reality, leading the wave of the times, let us work together to create a better tomorrow!");
document.write("						<\/p>");
document.write("					<\/div>");
document.write("				<\/div>");
document.write("				<div class=\"col-lg-4 col-md-6 col-sm-4 md-mb-20\">");
document.write("					<div class=\"footer-link\">");
document.write("						<h4>Useful Links<\/h4>");
document.write("						<ul>");
document.write("							<li>");
document.write("								<i class=\"fa-solid fa-angles-right\"><\/i>");
document.write("								<a href=\"index.html\" title=\"\">Home<\/a>");
document.write("							<\/li>");
document.write("							<li>");
document.write("								<i class=\"fa-solid fa-angles-right\"><\/i>");
document.write("								<a href=\"about.html\" title=\"\">About Us<\/a><\/li>");
document.write("							<li>");
document.write("								<i class=\"fa-solid fa-angles-right\"><\/i>");
document.write("								<a href=\"product.html\" title=\"\">Product<\/a>");
document.write("							<\/li>");
document.write("						<\/ul>");
document.write("					<\/div>");
document.write("				<\/div>");
document.write("				<div class=\"col-lg-4 col-md-6\">");
document.write("					<div class=\"contact-info\">");
document.write("						<h4>Useful Links<\/h4>");
document.write("						<div class=\"footer-tweets\">");
document.write("							<div class=\"tweets-icon\">");
document.write("								<i class=\"fa-solid fa-location-dot\"><\/i>");
document.write("							<\/div>");
document.write("							<div class=\"tweets-text mb-15\">");
document.write("								<p>1704-1706, 17th Floor, Block A, Bowcun New Town Commercial Center");
document.write("									(Huihai Plaza), No. 19, Sanlian Chuangye Road, Sanlian Community,");
document.write("									Longhua Street, Longhua District, Shenzhen");
document.write("								<\/p>");
document.write("							<\/div>");
document.write("						<\/div>");
document.write("						<div class=\"footer-tweets\">");
document.write("							<div class=\"tweets-icon\">");
document.write("								<i class=\"fa-solid fa-phone\"><\/i>");
document.write("							<\/div>");
document.write("							<div class=\"tweets-text mb\">");
document.write("								<p>13027961108<\/p>");
document.write("							<\/div>");
document.write("						<\/div>");
document.write("						<div class=\"footer-tweets\">");
document.write("							<div class=\"tweets-icon\">");
document.write("								<i class=\"fa-solid fa-envelope\"><\/i>");
document.write("							<\/div>");
document.write("							<div class=\"tweets-text\">");
document.write("								<p>guolink@guolink.com <\/p>");
document.write("							<\/div>");
document.write("						<\/div>");
document.write("					<\/div>");
document.write("				<\/div>");
document.write("			<\/div>");
document.write("		<\/div>");
document.write("	<\/section>");
document.write("	<div class=\"copy-area pt-30 pb-30\">");
document.write("		<div class=\"container\">");
document.write("			<div class=\"row\">");
document.write("				<div class=\"col-lg-12\">");
document.write("					<div class=\"copy-text text-center\">");
document.write("						<p>Copyright © 2023.Shenzhen guo-link Technology Co.,Ltd. All rights reserved.<\/p>");
document.write("					<\/div>");
document.write("				<\/div>");
document.write("			<\/div>");
document.write("		<\/div>");
document.write("	<\/div>");
document.write("<\/footer>");
