document.write("<header>");
document.write("	<div class=\"main-header-area\">");
document.write("		<div class=\"header-top-menu\">");
document.write("			<div class=\"container\">");
document.write("				<div class=\"row\">");
document.write("					<div class=\"col-lg-12 col-md-12 col-sm-12\">");
document.write("						<div class=\"top-left\">");
document.write("							<ul>");
document.write("								<li><i class=\"fa-solid fa-phone\"><\/i>13027961108<\/li>");
document.write("								<li><i class=\"fa-solid fa-clock\"><\/i>09:00 AM - 5:00 PM<\/li>");
document.write("							<\/ul>");
document.write("						<\/div>");
document.write("					<\/div>");
document.write("				<\/div>");
document.write("			<\/div>");
document.write("		<\/div>");
document.write("		<div class=\"mean-menu-wrapper header-middle\">");
document.write("			<div class=\"container\">");
document.write("				<div class=\"row align-items-center\">");
document.write("					<div class=\"col-lg-3 col-md-4 col-sm-4\">");
document.write("						<div class=\"logo\">");
document.write("							<a href=\"index.html\"><img class=\"img-fluid img_logo\" src=\".\/static\/image\/logo.png\" alt=\"logo\"><\/a>");
document.write("						<\/div>");
document.write("					<\/div>");
document.write("					<div class=\"col-lg-9 col-md-8 col-sm-7\">");
document.write("						<div class=\"canvas_open\">");
document.write("							<a href=\"#\"><i class=\"fas fa-bars\"><\/i><\/a>");
document.write("						<\/div>");
document.write("						<div class=\"mean-menu\">");
document.write("							<nav>");
document.write("								<ul>");
document.write("									<li><a href=\"index.html\" title=\"\">home<\/a><\/li>");
document.write("									<li><a href=\"about.html\" title=\"\">about<\/a><\/li>");
document.write("									<li><a href=\"product.html\" title=\"\">product<\/a><\/li>");
document.write("								<\/ul>");
document.write("							<\/nav>");
document.write("						<\/div>");
document.write("					<\/div>");
document.write("				<\/div>");
document.write("			<\/div>");
document.write("		<\/div>");
document.write("	<\/div>");
document.write("	<div class=\"mobile-menu-area\">");
document.write("		<div class=\"offcanvas_menu\">");
document.write("			<div class=\"offcanvas_menu_wrapper\">");
document.write("				<div class=\"canvas_close\">");
document.write("					<a href=\"javascript:void(0)\"><i class=\"fas fa-times\"><\/i><\/a>");
document.write("				<\/div>");
document.write("				<div id=\"menu\" class=\"text-left mt-50\">");
document.write("					<ul class=\"offcanvas_main_menu\">");
document.write("						<li class=\"menu-item-has-children active\"><span class=\"menu-expand\"><\/span>");
document.write("							<a href=\"index.html\">Home<\/a>");
document.write("						<\/li>");
document.write("						<li class=\"menu-item-has-children\">");
document.write("							<a href=\"about.html\">about<\/a>");
document.write("						<\/li>");
document.write("						<li class=\"menu-item-has-children\">");
document.write("							<a href=\"contact.html\">contact<\/a>");
document.write("						<\/li>");
document.write("					<\/ul>");
document.write("				<\/div>");
document.write("			<\/div>");
document.write("		<\/div>");
document.write("	<\/div>");
document.write("<\/header>");